export const historyCitys = [
    ["北京", "BJP", "beijing", "bj"],
    ["上海", "SHH", "shanghai", "sh"],
]
export const popularCitys = [
    ["北京", "BJP", "beijing", "bj"],
    ["上海", "SHH", "shanghai", "sh"],
    ["杭州", "HZH", "hangzhou", "hz"],
    ["广州", "GZQ", "guangzhou", "gz"],
    ["南京", "NJH", "nanjing", "nj"],
    ["成都", "CDW", "chengdu", "cd"],
    ["西安", "XAY", "xian", "xa"],
    ["郑州", "ZZF", "zhengzhou", "zz"],
    ["重庆", "CQW", "chongqing", "cq"],
    ["合肥", "HFH", "hefei", "hf"],
    ["汉口", "HKN", "hankou", "hk"],
    ["武汉", "WHN", "wuhan", "wh"],
    ["长沙", "CSQ", "changsha", "cs"],
    ["武昌", "WCN", "wuchang", "wc"],
    ["太原", "TYV", "taiyuan", "ty"],
    ["苏州", "SZH", "suzhou", "sz"],
    ["厦门", "XMS", "xiamen", "xm"],
    ["南昌", "NOG", "nanchang", "nc"],
    ["沈阳", "SYT", "shenyang", "sy"],
    ["天津", "TJP", "tianjing", "tj"],
    ["深圳", "SZQ", "shenzhen", "sz"],
]
