var a = {
    data: [
        {
            arrive_time: '22:00',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '15:50',
            time_used_up: '06:10',
            train_id: 'G147'
        },
        {
            arrive_time: '22:50',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '16:25',
            time_used_up: '06:25',
            train_id: 'G149'
        },
        {
            arrive_time: '22:35',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '16:40',
            time_used_up: '05:55',
            train_id: 'G169'
        },
        {
            arrive_time: '23:02',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '\u65e0',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '16:45',
            time_used_up: '06:17',
            train_id: 'G151'
        },
        {
            arrive_time: '21:36',
            business_seat: '',
            first_seat: '\u65e0',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u65e0',
            soft_sleep: '',
            start_times: '17:00',
            time_used_up: '04:36',
            train_id: 'G13'
        },
        {
            arrive_time: '23:11',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '17:16',
            time_used_up: '05:55',
            train_id: 'G153'
        },
        {
            arrive_time: '23:32',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '17:36',
            time_used_up: '05:56',
            train_id: 'G157'
        },
        {
            arrive_time: '23:54',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '17:46',
            time_used_up: '06:08',
            train_id: 'G159'
        },
        {
            arrive_time: '22:43',
            business_seat: '',
            first_seat: '\u65e0',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '18:00',
            time_used_up: '04:43',
            train_id: 'G15'
        },
        {
            arrive_time: '23:18',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '19:00',
            time_used_up: '04:18',
            train_id: 'G17'
        },
        {
            arrive_time: '23:40',
            business_seat: '',
            first_seat: '\u6709',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '',
            start_times: '19:08',
            time_used_up: '04:32',
            train_id: 'G21'
        },
        {
            arrive_time: '09:54',
            business_seat: '',
            first_seat: '',
            hard_seat: '\u65e0',
            hard_sleep: '\u65e0',
            no_sea: '\u65e0',
            second_seat: '',
            soft_sleep: '\u65e0',
            start_times: '19:10',
            time_used_up: '14:44',
            train_id: 'Z281'
        },
        {
            arrive_time: '07:26',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '2',
            no_sea: '\u65e0',
            second_seat: '\u65e0',
            soft_sleep: '\u6709',
            start_times: '19:22',
            time_used_up: '12:04',
            train_id: 'D701'
        },
        {
            arrive_time: '07:46',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '\u6709',
            no_sea: '',
            second_seat: '\u65e0',
            soft_sleep: '\u6709',
            start_times: '19:46',
            time_used_up: '12:00',
            train_id: 'D709'
        },
        {
            arrive_time: '11:00',
            business_seat: '',
            first_seat: '',
            hard_seat: '\u65e0',
            hard_sleep: '\u65e0',
            no_sea: '\u6709',
            second_seat: '',
            soft_sleep: '\u65e0',
            start_times: '20:05',
            time_used_up: '14:55',
            train_id: 'T109'
        },
        {
            arrive_time: '09:17',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '\u6709',
            no_sea: '',
            second_seat: '\u6709',
            soft_sleep: '\u6709',
            start_times: '21:16',
            time_used_up: '12:01',
            train_id: 'D703'
        },
        {
            arrive_time: '09:20',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '\u6709',
            no_sea: '11',
            second_seat: '\u6709',
            soft_sleep: '\u6709',
            start_times: '21:21',
            time_used_up: '11:59',
            train_id: 'D705'
        }
    ],
    success: true
}
