export const response = {
    data: [
        {
            arrive_time: '22:35',
            business_seat: '16',
            first_seat: '有',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '',
            start_times: '16:40',
            time_used_up: '05:55',
            train_id: 'G169'
        },
        {
            arrive_time: '23:02',
            business_seat: '11',
            first_seat: '有',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '无',
            second_seat: '有',
            soft_sleep: '',
            start_times: '16:45',
            time_used_up: '06:17',
            train_id: 'G151'
        },
        {
            arrive_time: '21:36',
            business_seat: '1',
            first_seat: '无',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '无',
            soft_sleep: '',
            start_times: '17:00',
            time_used_up: '04:36',
            train_id: 'G13'
        },
        {
            arrive_time: '23:11',
            business_seat: '有',
            first_seat: '有',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '',
            start_times: '17:16',
            time_used_up: '05:55',
            train_id: 'G153'
        },
        {
            arrive_time: '23:32',
            business_seat: '16',
            first_seat: '有',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '',
            start_times: '17:36',
            time_used_up: '05:56',
            train_id: 'G157'
        },
        {
            arrive_time: '22:43',
            business_seat: '8',
            first_seat: '1',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '',
            start_times: '18:00',
            time_used_up: '04:43',
            train_id: 'G15'
        },
        {
            arrive_time: '23:18',
            business_seat: '5',
            first_seat: '1',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '',
            start_times: '19:00',
            time_used_up: '04:18',
            train_id: 'G17'
        },
        {
            arrive_time: '23:40',
            business_seat: '15',
            first_seat: '有',
            hard_seat: '',
            hard_sleep: '',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '',
            start_times: '19:08',
            time_used_up: '04:32',
            train_id: 'G21'
        },
        {
            arrive_time: '09:54',
            business_seat: '',
            first_seat: '',
            hard_seat: '无',
            hard_sleep: '无',
            no_sea: '有',
            second_seat: '',
            soft_sleep: '无',
            start_times: '19:10',
            time_used_up: '14:44',
            train_id: 'Z281'
        },
        {
            arrive_time: '07:26',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '有',
            no_sea: '有',
            second_seat: '有',
            soft_sleep: '有',
            start_times: '19:22',
            time_used_up: '12:04',
            train_id: 'D701'
        },
        {
            arrive_time: '07:41',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '有',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '有',
            start_times: '19:36',
            time_used_up: '12:05',
            train_id: 'D707'
        },
        {
            arrive_time: '07:46',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '有',
            no_sea: '',
            second_seat: '有',
            soft_sleep: '有',
            start_times: '19:46',
            time_used_up: '12:00',
            train_id: 'D709'
        },
        {
            arrive_time: '11:00',
            business_seat: '',
            first_seat: '',
            hard_seat: '无',
            hard_sleep: '无',
            no_sea: '有',
            second_seat: '',
            soft_sleep: '无',
            start_times: '20:05',
            time_used_up: '14:55',
            train_id: 'T109'
        },
        {
            arrive_time: '09:20',
            business_seat: '',
            first_seat: '',
            hard_seat: '',
            hard_sleep: '有',
            no_sea: '有',
            second_seat: '有',
            soft_sleep: '有',
            start_times: '21:21',
            time_used_up: '11:59',
            train_id: 'D705'
        }
    ],
    success: true
}
